// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmyjfflvxgllibbybwbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteWpmZmx2eGdsbGliYnlid2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDQ1NjMsImV4cCI6MjA2OTI4MDU2M30.JFFaYWJJXsouF2S-FKwSqQBif9n5BhfClNlWIO4kAMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});